# -*- coding: utf-8 -*-
"""Smart Agriculture System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sa9CwM_l2U0yaICda_Uc7B2fteFU6xCo
"""

# Sample ML model for predicting crop yield
from sklearn.linear_model import LinearRegression
import numpy as np

# Simulated sensor data
X = np.random.rand(100, 5)  # Moisture, Temp, Humidity, Light, pH
y = np.random.rand(100) * 100  # Crop yield in kg

model = LinearRegression()
model.fit(X, y)

# Predict
new_data = np.array([[0.3, 25, 60, 200, 6.5]])
print("Predicted Yield:", model.predict(new_data)[0])