# -*- coding: utf-8 -*-
"""qiskit_demo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MSqlZT7uHaRFVqCDRlU_BZ6dAnnoA4Bv
"""

# Quantum AI for Drug Discovery Optimization
from qiskit import QuantumCircuit, transpile
from qiskit_aer import AerSimulator
from qiskit.visualization import plot_histogram
import matplotlib.pyplot as plt

def molecular_entanglement_circuit():
    """Creates a quantum circuit simulating molecular bonds"""
    qc = QuantumCircuit(2, 2)

    # Create entangled state (simulating molecular bond)
    qc.h(0)          # Hadamard gate (superposition)
    qc.cx(0, 1)      # CNOT gate (entanglement)
    qc.measure_all()  # Measure all qubits

    return qc

# 1. Create and visualize the circuit
qc = molecular_entanglement_circuit()
print("Quantum Circuit:")
print(qc.draw(output='text'))

# 2. Simulate on quantum backend
simulator = AerSimulator()
compiled_circuit = transpile(qc, simulator)
result = simulator.run(compiled_circuit, shots=1024).result()

# 3. Get and plot results
counts = result.get_counts(qc)
print("\nMeasurement Results:", counts)
plot_histogram(counts)
plt.title("Quantum Simulation of Molecular Bond States")
plt.show()